// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Login() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div><section class=\"w-full px-8 py-16 bg-gray-100 xl:px-8 flex items-center\" id=\"form-container\"><div class=\"max-w-5xl mx-auto\"><div class=\"flex flex-col items-center md:flex-row\"><form hx-post=\"/login\" hx-target=\"#form-container\" hx-swap=\"outerHTML\"><div class=\"w-full mt-16 md:mt-0 \"><div class=\"relative z-10 h-auto p-8 py-10 overflow-hidden bg-white border-b-2 border-gray-300 rounded-lg shadow-2xl px-7\" data-rounded=\"rounded-lg\" data-rounded-max=\"rounded-full\"><h3 class=\"mb-6 text-2xl font-medium text-center\">Log in to your Account</h3><input type=\"text\" name=\"username\" id=\"username\t\" class=\"block w-full px-4 py-3 mb-4 border-2 border-transparent border-gray-200 rounded-lg focus:ring focus:ring-blue-500 focus:outline-none\" data-rounded=\"rounded-lg\" data-primary=\"blue-500\" placeholder=\"Username\"> <input type=\"password\" name=\"password\" id=\"password\" class=\"block w-full px-4 py-3 mb-4 border-2 border-transparent border-gray-200 rounded-lg focus:ring focus:ring-blue-500 focus:outline-none\" data-rounded=\"rounded-lg\" data-primary=\"blue-500\" placeholder=\"Password\"><div class=\"block\"><button class=\"w-full px-3 py-4 font-medium text-white bg-blue-600 rounded-lg\" data-primary=\"blue-600\" data-rounded=\"rounded-lg\">Log me in</button></div><p class=\"w-full mt-4 text-sm text-center text-gray-500\">Log in with a different <a href=\"#_\" class=\"text-blue-500 underline\">service/account</a></p><p class=\"w-full mt-4 text-sm text-center text-gray-500\">Don't have an account? <a href=\"/signup\" class=\"text-blue-500 underline\">Signup</a></p></div></div></form></div></div></section></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func LoginSuccess(name string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"min-h-screen flex items-center justify-center bg-gray-100\" id=\"login-success-container\"><div class=\"bg-white p-8 rounded shadow-md w-full max-w-md text-center\" id=\"LoginSuccessMsg\"><h2 class=\"text-green-600 text-2xl font-bold mb-2\">Welcome back!</h2><p class=\"text-gray-700 mb-6\">You've logged in successfully, <span class=\"font-semibold\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `layouts/components/login.templ`, Line: 44, Col: 98}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span>.</p><div class=\"flex justify-center items-center\"><a href=\"/\" class=\"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline inline-block mr-2\">Go to Dashboard</a> <a href=\"/profile\" class=\"bg-violet-500 hover:bg-violet-700  text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline \">View Profile</a></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
